### ISSUE TITLE
ability to use a custom versionCode

### ISSUE THREAD

**Issue by sylvek** [Jems22/fastlane-plugin-increment_version_code#1]
Hi, first of all, thank you for your plugin !

in some case, it may be useful to increment the versionCode by an external input.
(for example, in my case, i retrieve my versionCode from my Appaloosa store)

inspired from your code, this is my humble contribution.
Regards

```
def self.run(params)
        version_code = params[:version_code]
        app_folder_name = params[:app_folder_name]
        temp_file = Tempfile.new('fastlaneIncrementVersionCode')
        Dir.glob("**/#{app_folder_name}/build.gradle") do |file_name|
          UI.message(" -> Found a build.gradle file at path: (#{file_name})!")
          text = File.read(file_name)
          new_contents = text.gsub(/versionCode [0-9]*/, "versionCode #{version_code}")
          UI.success("☝️ Version code has been changed to #{version_code}") unless text == new_contents
          File.open(file_name, "w") {|file| file.puts new_contents }
        end
      end
```

**Comment by Jems22** [comment]
Hi Sylvek.
Thanks for your feed back.
I just updated the plugin (v0.3.0) to let you set a custom version code (instead of increasing it)

You can use the new `version_code` param in you fastfile to set the version code value.
`increment_version_code(version_code:280)`

Let me know if everything is ok for you.

**Comment by sylvek** [comment]
c'est parfait merci ! :)
